name: Test scriptum-front
on: [push, workflow_dispatch]
jobs:
  telegram-notify:
    name: Send Telegram notification
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            Repository: ${{ github.repository }}
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
  install-cache:
    name: Install cache
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-ci.outputs.key }}
    steps:
      - name: Get the repository code
        uses: actions/checkout@v5
      - name: Set cache key
        id: cache-ci
        run: echo "key=node-modules-${{ hashFiles('**/package-lock.json') }}" >> $GITHUB_OUTPUT

      - name: Cache ci dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ steps.cache-ci.outputs.key }}
  eslint-check:
    name: Eslint check
    runs-on: ubuntu-latest
    needs: ['install-cache']
    steps:
      - name: Get the repository code
        uses: actions/checkout@v5
      - name: Restore npm cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ needs.install-cache.outputs.cache-key }}
      - name: Install dependencies
        run: npm ci
      - name: Run eslint check
        run: npm run lint:eslint:fix
  prettier-check:
    name: Prettier check
    runs-on: ubuntu-latest
    needs: ['install-cache']
    steps:
      - name: Get the repository code
        uses: actions/checkout@v5
      - name: Restore npm cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ needs.install-cache.outputs.cache-key }}
      - name: Install dependencies
        run: npm ci
      - name: Run prettier fix
        run: npm run format:fix
  stylelint-check:
    name: Stylelint check
    needs: ['install-cache']
    runs-on: ubuntu-latest
    steps:
      - name: Get the repository code
        uses: actions/checkout@v5
      - name: Restore npm cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ needs.install-cache.outputs.cache-key }}
      - name: Install dependencies
        run: npm ci
      - name: Run stylelint fix
        run: npm run lint:stylelint:fix
  typescript-check:
    name: TypeScript check
    needs: ['install-cache']
    runs-on: ubuntu-latest
    steps:
      - name: Get the repository code
        uses: actions/checkout@v5
      - name: Restore npm cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ needs.install-cache.outputs.cache-key }}
      - name: Install dependencies
        run: npm ci
      - name: Run TypeScript check
        run: npm run ts:check

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      ['install-cache', 'eslint-check', 'prettier-check', 'stylelint-check', 'typescript-check']
    steps:
      - name: Get the repository code
        uses: actions/checkout@v5
      - name: Restore npm cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ needs.install-cache.outputs.cache-key }}
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run build
        env:
          NEXT_PUBLIC_API_URL: ${{ vars.NEXT_PUBLIC_API_URL }}

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    environment: production
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        env:
          EXTERNAL_PORT: ${{ vars.EXTERNAL_PORT }}
          NEXT_PUBLIC_API_URL: ${{ vars.NEXT_PUBLIC_API_URL }}
        with:
          host: ${{ vars.SSH_HOST }}
          port: ${{ vars.SSH_PORT }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          envs: EXTERNAL_PORT, NEXT_PUBLIC_API_URL
          script: |
            cd ${{ vars.PROJECT_DIR }}
            git stash
            git checkout dev
            git pull origin dev
            docker compose -f docker-compose.yaml up --build -d
